app = "uni-ai"
primary_region = 'sjc'

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[http_service]
  internal_port = 8100
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  LANG="C.UTF-8"
  
[mounts]
  source = "uni_ai_cache"
  destination = "/app/cache"